# Generated by Django 4.0.4 on 2022-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InflectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_field', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_component_url', models.FileField(null=True, upload_to='media')),
                ('component_url', models.FileField(null=True, upload_to='media')),
                ('types', models.CharField(max_length=20)),
                ('sub_type', models.CharField(max_length=30)),
                ('length', models.DurationField()),
                ('business', models.ManyToManyField(to='api.business')),
                ('inflection_time', models.ManyToManyField(to='api.inflectiontime')),
            ],
        ),
    ]
