# Generated by Django 4.0.4 on 2022-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_component_delete_inflectiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_field', models.DurationField()),
            ],
        ),
    ]
