# Generated by Django 4.0.4 on 2022-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inflectiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_component_url', models.FileField(null=True, upload_to='media')),
                ('component_url', models.FileField(null=True, upload_to='media')),
                ('types', models.CharField(max_length=20)),
                ('sub_type', models.CharField(max_length=30)),
                ('length', models.DurationField()),
                ('business', models.ManyToManyField(to='api.business')),
            ],
        ),
    ]
