# Generated by Django 4.0.4 on 2022-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='inflection_time',
            field=models.ManyToManyField(to='api.inflectiontime'),
        ),
    ]
