# Generated by Django 4.0.4 on 2022-06-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_component_inflection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='length',
        ),
    ]
