# Generated by Django 4.0.4 on 2022-06-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='overlays',
        ),
        migrations.DeleteModel(
            name='Overlays',
        ),
    ]
