# Generated by Django 4.0.4 on 2022-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_remove_template_overlays_delete_overlays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ManyToManyField(to='template.logos')),
            ],
        ),
    ]
