# Generated by Django 4.0.4 on 2022-06-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_overlays'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='overlays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='template.overlays'),
            preserve_default=False,
        ),
    ]
