# Generated by Django 4.0.4 on 2022-06-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_template_overlays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextElement',
        ),
    ]
