# Generated by Django 4.0.4 on 2022-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_delete_textelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('font', models.CharField(max_length=30)),
                ('font_size', models.CharField(max_length=10)),
                ('position_x', models.CharField(max_length=10)),
                ('position_y', models.CharField(max_length=10)),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='overlays',
            name='text_element',
            field=models.ManyToManyField(to='template.textelement'),
        ),
    ]
